# Generated by Django 2.2.4 on 2019-11-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190901_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='country',
        ),
        migrations.DeleteModel(
            name='Strana',
        ),
    ]
