# Generated by Django 2.2.4 on 2019-11-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20191108_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(error_messages={'invalid_image': 'It is wrong image format', 'required': 'It is required field'}, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Post', verbose_name='Пост'),
        ),
    ]
