# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('it', 'не знаю')], default='it', max_length=9),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
