# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161215_2339'),
        ('blog', '0003_auto_20170107_1517'),
    ]

    operations = [
    ]
