# Generated by Django 2.2.4 on 2019-11-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='gender',
        ),
    ]
